# docker-compose.yml
version: "3"
services:
  app:
    container_name: api
    build: .
    depends_on:
      - postgres-db
    environment:
      PORT: 9081
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "9081:9081"
    command: yarn start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres-db:
    container_name: db
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
